Recommend kiwi-systemdeps-containers
SUSE/kiwi_sle15 pull request #1
Opened 2021-04-12 15:23 UTC by davidcassany

This commit recommends kiwi-systemdeps-containers instead of a hard
requirement in kiwi-systemdeps package for SLE builds. This is needed
because the containers tool chain is spread in different SLE modules.

2021-04-12 15:27 UTC, davidcassany commented
I did a build of this code [here](https://build.suse.de/package/show/home:dcassany:15-SP1:python-kiwi/python-kiwi) for several leap versions and SLE service packs. You can check requirements and recommends for  `kiwi-systemdeps` of all these versions.

2021-04-13 09:08 UTC, schaefi requested changes
Thanks looks good :+1: just the rhel condition needs a change I think

2021-04-13 09:08 UTC, schaefi commented on package/python-kiwi-spec-template
> +%if 0%{?fedora} || 0%{?rhel} || 0%{?sle_version} >= 150000 && !0%{?is_opensuse}
For the rhel part this should be ```0%{?rhel} >= 8```

I remember Neal saying that recommends only works starting with rhel >=8

2021-04-13 11:40 UTC, davidcassany commented
@schaefi now I redid the change to ensure the behavior change is only applied to SLE, all others are kept as they were.

2021-04-13 11:51 UTC, schaefi approved these changes
That looks great to me :+1:

2021-04-13 15:28 UTC, merged

2021-04-13 15:28 UTC, davidcassany commented
@schaefi the question now is how to proceed with this change, shall we try to run another submission to SLE shortly after the current one is released or shall we wait until our next regular update? I'd wait until there is another regular update unless we have to release sooner to fix some bug. That makes sense to you?

2021-04-13 15:33 UTC, schaefi commented
I would also wait for the next update window